# Descendant matrix builder (taxonomy ancestor/descendant closure)

we build:
   - parent.npy / depth.npy / root_id.npy  (optional but useful)
   - descendant_matrix.npy                (M: ancestor/descendant closure)

 Matrix definition (same as your old ETE3 version):
   M[i, j] = 1  iff  node j is node i OR a descendant of node i
 

In [1]:
import json
import numpy as np
from pathlib import Path
from collections import deque
from tqdm import tqdm
# --------------------------
# Paths
# --------------------------
DATASET_DIR = Path(
    "/home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training"
    "/level_97/silva-138.2/incomplete_silva_sintax/dataset_full_top999"
)

VOCAB_PATH  = DATASET_DIR / "taxonomy_vocab.json"
NESTED_PATH = DATASET_DIR / "taxonomy_nested.json"

assert VOCAB_PATH.exists(), f"Missing: {VOCAB_PATH}"
assert NESTED_PATH.exists(), f"Missing: {NESTED_PATH}"

# Save derived matrices into a subfolder (recommended)
TREE_DIR = DATASET_DIR / "tree_artifacts"
TREE_DIR.mkdir(parents=True, exist_ok=True)

print("DATASET_DIR =", DATASET_DIR)
print("TREE_DIR    =", TREE_DIR)

# --------------------------
# Load vocab + nested tree
# --------------------------
names = json.load(open(VOCAB_PATH, "r"))
name2idx = {nm: i for i, nm in enumerate(names)}
N = len(names)

taxonomy_nested = json.load(open(NESTED_PATH, "r"))

print("N taxonomy nodes =", N)
print("Top-level clades:", list(taxonomy_nested.keys())[:10])

DATASET_DIR = /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_silva_sintax/dataset_full_top999
TREE_DIR    = /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_silva_sintax/dataset_full_top999/tree_artifacts
N taxonomy nodes = 6929
Top-level clades: ['k:Bacteria', 'k:Archaea']


In [ ]:

# ============================================================
# 1) Build parent pointers and children adjacency from nested dict
# ============================================================

def build_parent_children_from_nested(taxonomy_nested, name2idx):
    """
    Build parent pointers and children adjacency using taxonomy_nested.json.

    parent[i] = parent index of node i, or -1 if i is a top-level clade
    children[i] = list of child indices
    """
    N = len(name2idx)
    parent = np.full(N, -1, dtype=np.int32)
    children = [[] for _ in range(N)]

    def dfs(subtree: dict, parent_name=None):
        for node_name, child_dict in subtree.items():
            if node_name not in name2idx:
                # Should not happen if nested tree was built from vocab;
                # keep simple and skip.
                continue

            i = name2idx[node_name]

            if parent_name is not None and parent_name in name2idx:
                p = name2idx[parent_name]
                parent[i] = p
                children[p].append(i)

            if isinstance(child_dict, dict) and child_dict:
                dfs(child_dict, parent_name=node_name)

    # forest: multiple top-level clades allowed
    dfs(taxonomy_nested, parent_name=None)
    return parent, children


parent, children = build_parent_children_from_nested(taxonomy_nested, name2idx)
roots = [i for i in np.where(parent == -1)[0].tolist() if names[i] in taxonomy_nested]

print("Number of roots (top-level clades) =", len(roots))
print("First 10 roots:", [names[i] for i in roots[:10]])


# ============================================================
# 2) Compute depth (optional but convenient for debugging)
# ============================================================

def compute_depth(children, roots):
    """
    BFS depth from each root.
    Any unreachable nodes (e.g., appended k:UNK) are assigned depth=0
    and treated as singleton components.
    """
    N = len(children)
    depth = np.full(N, -1, dtype=np.int32)

    q = deque()
    for r in roots:
        depth[r] = 0
        q.append(r)

    while q:
        u = q.popleft()
        for v in children[u]:
            depth[v] = depth[u] + 1
            q.append(v)

    # Unreachable nodes: set depth=0 (singleton)
    bad = np.where(depth < 0)[0]
    if bad.size > 0:
        depth[bad] = 0

    return depth



depth = compute_depth(children, roots)

if (depth < 0).any():
    bad = np.where(depth < 0)[0]
    print("WARNING: some nodes unreachable (unexpected). Count:", len(bad))
    print("Examples:", [names[i] for i in bad[:10]])
else:
    print("Depth computed for all nodes.")
    print("Depth min/max:", int(depth.min()), int(depth.max()))


# ============================================================
# 3) Build descendant-closure matrix M
#    M[i, j] = 1 iff j is i or a descendant of i (same as old ETE3 code)
# ============================================================

def euler_tour_times(children, roots):
    """
    Compute entry/exit times (tin/tout) for each node.

    For nodes reachable from the forest roots, we do a DFS Euler tour.
    For unreachable nodes (e.g., appended k:UNK), we assign them unique
    singleton intervals so that:
      - they are ancestor/descendant only of themselves
      - they do not become ancestor/descendant of real nodes by accident
    """
    N = len(children)
    tin = np.full(N, -1, dtype=np.int32)
    tout = np.full(N, -1, dtype=np.int32)
    t = 0

    def dfs(u):
        nonlocal t
        tin[u] = t
        t += 1
        for v in children[u]:
            dfs(v)
        tout[u] = t
        t += 1

    # DFS on reachable forest
    for r in roots:
        if tin[r] == -1:
            dfs(r)

    # Assign singleton Euler intervals to unreachable nodes
    bad = np.where(tin < 0)[0]
    for u in bad:
        tin[u] = t
        t += 1
        tout[u] = t
        t += 1

    return tin, tout


tin, tout = euler_tour_times(children, roots)

def build_descendant_matrix_dense(tin, tout, dtype=np.uint8):
    """
    Dense descendant-closure matrix:
      M[i, j] = 1 iff i is ancestor of j (including i==j)
    """
    N = len(tin)
    M = np.zeros((N, N), dtype=dtype)
    for i in tqdm(range(N), desc="Building descendant matrix (dense)"):
        # vectorized ancestor test across all j
        M[i, :] = ((tin[i] <= tin) & (tout <= tout[i])).astype(dtype)
    return M


M = build_descendant_matrix_dense(tin, tout, dtype=np.uint8)

print("Descendant matrix shape:", M.shape, "dtype:", M.dtype)
print("Diagonal sum (should be N):", int(np.trace(M)))
print("Nonzero entries:", int(M.sum()))


# ============================================================
# 4) Save artifacts
# ============================================================

np.save(TREE_DIR / "parent.npy", parent)
np.save(TREE_DIR / "depth.npy", depth)
np.save(TREE_DIR / "tin.npy", tin)
np.save(TREE_DIR / "tout.npy", tout)

desc_path = TREE_DIR / "descendant_matrix.npy"
np.save(desc_path, M)
print("Saved:", desc_path)

# Minimal README for this folder (optional but recommended)
readme_path = TREE_DIR / "README_descendants.md"
with open(readme_path, "w") as f:
    f.write(
        "# Descendant matrix (ancestor/descendant closure)\n\n"
        "Files in this folder are derived from taxonomy_nested.json and taxonomy_vocab.json.\n\n"
        "## descendant_matrix.npy\n"
        "Let `names = taxonomy_vocab.json` (length N).\n"
        "The matrix `M` has shape [N, N] and is defined as:\n"
        "`M[i, j] = 1` iff node `names[j]` is equal to or a descendant of node `names[i]`.\n\n"
        "This matches the old ETE3 implementation, but uses an Euler tour (tin/tout) for speed.\n"
    )
print("Saved:", readme_path)



NameError: name 'taxonomy_nested' is not defined

In [ ]:

parent, children = build_parent_children_from_nested(taxonomy_nested, name2idx)
roots = [i for i in np.where(parent == -1)[0].tolist() if names[i] in taxonomy_nested]

print("Number of roots (top-level clades) =", len(roots))
print("First 10 roots:", [names[i] for i in roots[:10]])


M = build_descendant_matrix_dense(tin, tout, dtype=np.uint8)

print("Descendant matrix shape:", M.shape, "dtype:", M.dtype)
print("Diagonal sum (should be N):", int(np.trace(M)))
print("Nonzero entries:", int(M.sum()))


# ============================================================
# 4) Save artifacts
# ============================================================

np.save(TREE_DIR / "parent.npy", parent)
np.save(TREE_DIR / "depth.npy", depth)
np.save(TREE_DIR / "tin.npy", tin)
np.save(TREE_DIR / "tout.npy", tout)

desc_path = TREE_DIR / "descendant_matrix.npy"
np.save(desc_path, M)
print("Saved:", desc_path)

# Minimal README for this folder (optional but recommended)
readme_path = TREE_DIR / "README_descendants.md"
with open(readme_path, "w") as f:
    f.write(
        "# Descendant matrix (ancestor/descendant closure)\n\n"
        "Files in this folder are derived from taxonomy_nested.json and taxonomy_vocab.json.\n\n"
        "## descendant_matrix.npy\n"
        "Let `names = taxonomy_vocab.json` (length N).\n"
        "The matrix `M` has shape [N, N] and is defined as:\n"
        "`M[i, j] = 1` iff node `names[j]` is equal to or a descendant of node `names[i]`.\n\n"
        "This matches the old ETE3 implementation, but uses an Euler tour (tin/tout) for speed.\n"
    )
print("Saved:", readme_path)

# testing decendant matrix

In [4]:


def show_descendants(label, names, M_tensor, max_print=50):
    """
    Print all descendants of taxonomy label using the descendant matrix M.
    - label: string (e.g., 'f:Lachnospiraceae')
    - names: vocab list (taxonomy_vocab.json)
    - M_tensor: descendant closure matrix [N, N] (numpy array or torch tensor)
    """
    # handle numpy or torch
    if hasattr(M_tensor, "cpu"):  # torch tensor
        row = M_tensor[names.index(label)].cpu().numpy()
    else:  # numpy
        row = M_tensor[names.index(label)]

    descendant_indices = np.where(row == 1)[0]
    descendant_names = [names[j] for j in descendant_indices]

    print(f"\nDESCENDANTS of '{label}' (including itself):")
    print(f"Total: {len(descendant_names)}")

    for nm in descendant_names[:max_print]:
        print("  -", nm)

    if len(descendant_names) > max_print:
        print(f"... (showing first {max_print} of {len(descendant_names)})")


# Example inspections (edit freely)
#show_descendants("f:Lachnospiraceae", names, M, max_print=50)
show_descendants("g:Roseburia", names, M, max_print=50)
show_descendants("k:UNK", names, M, max_print=20)



DESCENDANTS of 'g:Roseburia' (including itself):
Total: 3
  - g:Roseburia
  - s:Lachnospiraceae_bacterium_feline_oral_taxon_021
  - s:Roseburia_sp._499

DESCENDANTS of 'k:UNK' (including itself):
Total: 1
  - k:UNK


# Extending the taxonomy tree with per-rank UNK nodes

This section augments the base taxonomy tree with one UNK node per rank 

(k:UNK, p:UNK, ..., s:UNK) in order to support per-rank taxonomy prediction

and hierarchical regularization in the OTU+Taxa foundation model.

In [6]:
# --------------------------
# Paths (same tree_artifacts directory)
# --------------------------
TREE_DIR = DATASET_DIR / "tree_artifacts"

BASE_VOCAB_PATH = DATASET_DIR / "taxonomy_vocab.json"
BASE_M_PATH     = TREE_DIR / "descendant_matrix.npy"

NEW_VOCAB_PATH  = TREE_DIR / "taxonomy_vocab_with_unk.json"
NEW_M_PATH      = TREE_DIR / "descendant_matrix_with_unk.npy"
RANK_IDX_PATH   = TREE_DIR / "rank_idx.npy"

# --------------------------
# Load base vocab and matrix
# --------------------------
with open(BASE_VOCAB_PATH, "r") as f:
    vocab_old = json.load(f)

M_old = np.load(BASE_M_PATH)
T_old = len(vocab_old)

assert M_old.shape == (T_old, T_old), "Mismatch between vocab and descendant matrix"

print(f"Loaded base taxonomy: T_old={T_old}")


Loaded base taxonomy: T_old=6929


In [ ]:
# --------------------------
# Rank mapping (for base vocab)
# --------------------------
RANK_CHAR_TO_IDX = {"k":0, "p":1, "c":2, "o":3, "f":4, "g":5, "s":6}
R = 7

rank_idx_old = np.empty(T_old, dtype=np.int64)
for i, name in enumerate(vocab_old):
    c = name[0].lower()
    if c not in RANK_CHAR_TO_IDX:
        raise ValueError(f"Cannot infer rank from token: {name}")
    rank_idx_old[i] = RANK_CHAR_TO_IDX[c]

# --------------------------
# Extend vocabulary (only add missing UNKs)
#   Base already has k:UNK, so we only append p..s UNK if missing.
# --------------------------
desired_unk = [f"{r}:UNK" for r in ["k","p","c","o","f","g","s"]]
have = set(vocab_old)

unk_tokens_to_add = [tok for tok in desired_unk if tok not in have]
vocab_new = vocab_old + unk_tokens_to_add
T_new = len(vocab_new)

with open(NEW_VOCAB_PATH, "w") as f:
    json.dump(vocab_new, f, indent=2)

print(f"Extended vocab saved: T_new={T_new} (added {len(unk_tokens_to_add)} UNKs)")
print("UNKs added:", unk_tokens_to_add)

# Build rank_idx for extended vocab
rank_idx_new = np.empty(T_new, dtype=np.int64)
rank_idx_new[:T_old] = rank_idx_old

for j, tok in enumerate(unk_tokens_to_add, start=T_old):
    c = tok[0].lower()
    rank_idx_new[j] = RANK_CHAR_TO_IDX[c]

# --------------------------
# Build extended descendant matrix
# --------------------------
M_new = np.zeros((T_new, T_new), dtype=M_old.dtype)
M_new[:T_old, :T_old] = M_old

# Helper: get UNK id for each rank from vocab_new
unk_id_by_rank = {}
for tok in desired_unk:
    # guaranteed to exist either in base or appended
    idx = vocab_new.index(tok)
    unk_id_by_rank[tok[0].lower()] = idx

# 1) Link each UNK_r (r>=1) as child of ALL REAL nodes at rank r-1
#    NOTE: "real nodes" here means base vocabulary nodes. If base already
#    contains k:UNK, it is NOT a "real" parent class; we typically exclude it.
for r_char, r in [("p",1), ("c",2), ("o",3), ("f",4), ("g",5), ("s",6)]:
    unk_id = unk_id_by_rank[r_char]      # global id in vocab_new
    parent_rank = r - 1

    # parents among BASE nodes only (0..T_old-1)
    parents = np.where(rank_idx_old == parent_rank)[0]

    # optional: exclude k:UNK from being a parent of p:UNK
    # (base may include k:UNK; we don't want it in "parents")
    if parent_rank == 0 and "k:UNK" in vocab_old:
        kunk_id_base = vocab_old.index("k:UNK")
        parents = parents[parents != kunk_id_base]

    if parents.size == 0:
        print(f"[WARN] No parents found at rank {parent_rank} for {r_char}:UNK")
        continue

    M_new[parents, unk_id] = 1

# 2) Chain UNKs: k:UNK → p:UNK → ... → s:UNK
#    This uses the ids from vocab_new.
chain = ["k","p","c","o","f","g","s"]
for a, b in zip(chain[:-1], chain[1:]):
    M_new[unk_id_by_rank[a], unk_id_by_rank[b]] = 1

# 3) Closure: self-descendants
np.fill_diagonal(M_new, 1)

# --------------------------
# Save artifacts
# --------------------------
np.save(NEW_M_PATH, M_new)
np.save(RANK_IDX_PATH, rank_idx_new)

print("Saved UNK-extended hierarchy artifacts:")
print(" -", NEW_VOCAB_PATH)
print(" -", NEW_M_PATH)
print(" -", RANK_IDX_PATH)

Extended vocab saved: T_new=6935 (added 6 UNKs)
UNKs added: ['p:UNK', 'c:UNK', 'o:UNK', 'f:UNK', 'g:UNK', 's:UNK']
Saved UNK-extended hierarchy artifacts:
 - /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_silva_sintax/dataset_full_top999/tree_artifacts/taxonomy_vocab_with_unk.json
 - /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_silva_sintax/dataset_full_top999/tree_artifacts/descendant_matrix_with_unk.npy
 - /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_silva_sintax/dataset_full_top999/tree_artifacts/rank_idx.npy


In [12]:
from collections import Counter
c = Counter(vocab_old)
dups = {k:v for k,v in c.items() if v>1}
print("Duplicates in base vocab:", dups)
print("k:UNK count in base vocab:", c.get("k:UNK", 0))


Duplicates in base vocab: {}
k:UNK count in base vocab: 1


In [13]:
# Load the extended vocab and matrix
vocab_new = json.load(open(NEW_VOCAB_PATH))
M_new = np.load(NEW_M_PATH)

T_new = len(vocab_new)
T_old = T_new - 7   # since last 7 tokens are the UNKs

# Extract the 7×7 UNK submatrix
M_unk = M_new[T_old:T_new, T_old:T_new]

print("UNK tokens:")
for i, name in enumerate(vocab_new[T_old:T_new]):
    print(f"{T_old+i}: {name}")

print("\n7x7 descendant matrix for UNK tokens (rows=ancestors, cols=descendants):")
print(M_unk)


UNK tokens:
6928: k:UNK
6929: p:UNK
6930: c:UNK
6931: o:UNK
6932: f:UNK
6933: g:UNK
6934: s:UNK

7x7 descendant matrix for UNK tokens (rows=ancestors, cols=descendants):
[[1 1 0 0 0 0 0]
 [0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]


In [ ]:
# ----------------------------
# Load vocab + matrix
# ----------------------------
vocab_new = json.load(open(NEW_VOCAB_PATH))
M_new = np.load(NEW_M_PATH)

T_new = len(vocab_new)
T_old = T_new - 7   # assuming last 7 tokens are the UNKs

print(f"T_old = {T_old}, T_new = {T_new}")

# ----------------------------
# Find index of p:UNK
# ----------------------------
try:
    idx_p_unk = vocab_new.index("p:UNK")
except ValueError:
    raise ValueError("'p:UNK' not found in vocab_new. Check naming.")

print(f"Index of 'p:UNK' = {idx_p_unk}")

# ----------------------------
# Find all parents of p:UNK
# (rows where M_new[parent, idx_p_unk] == 1)
# ----------------------------
parents_idx = np.where(M_new[:, idx_p_unk] == 1)[0]

print("\nParents of 'p:UNK' (rows where M_new[parent, 'p:UNK'] == 1):")
for p in parents_idx:
    print(f"  {p:6d}  {vocab_new[p]}")

# ----------------------------
# check specifically Archaea, Bacteria, k:UNK
# ----------------------------
names_to_check = ["k:Archaea", "k:Bacteria", "k:UNK"]
print("\nCheck specific expected parents:")
for name in names_to_check:
    if name in vocab_new:
        idx = vocab_new.index(name)
        connected = bool(M_new[idx, idx_p_unk] == 1)
        print(f"  {name:10s}  idx={idx:6d}  -> p:UNK edge: {connected}")
    else:
        print(f"  {name:10s}  NOT FOUND in vocab_new")

T_old = 6928, T_new = 6935
Index of 'p:UNK' = 6929

Parents of 'p:UNK' (rows where M_new[parent, 'p:UNK'] == 1):
    3494  k:Archaea
    3495  k:Bacteria
    6928  k:UNK
    6929  p:UNK

Check specific expected parents:
  k:Archaea   idx=  3494  -> p:UNK edge: True
  k:Bacteria  idx=  3495  -> p:UNK edge: True
  k:UNK       idx=  6928  -> p:UNK edge: True


# creating the decendent matrix for the genus corrupted version of the dataset

In [3]:
import json
import numpy as np
from pathlib import Path
from collections import deque
from tqdm import tqdm

In [4]:
def build_parent_children_from_nested(taxonomy_nested, name2idx):
    """
    Build parent pointers and children adjacency using taxonomy_nested.json.

    parent[i] = parent index of node i, or -1 if i is a top-level clade
    children[i] = list of child indices
    """
    N = len(name2idx)
    parent = np.full(N, -1, dtype=np.int32)
    children = [[] for _ in range(N)]

    def dfs(subtree: dict, parent_name=None):
        for node_name, child_dict in subtree.items():
            if node_name not in name2idx:
                continue

            i = name2idx[node_name]

            if parent_name is not None and parent_name in name2idx:
                p = name2idx[parent_name]
                parent[i] = p
                children[p].append(i)

            if isinstance(child_dict, dict) and child_dict:
                dfs(child_dict, parent_name=node_name)

    dfs(taxonomy_nested, parent_name=None)
    return parent, children

def compute_depth(children, roots):
    """
    BFS depth from each root.
    Any unreachable nodes (e.g., appended k:UNK) are assigned depth=0
    and treated as singleton components.
    """
    N = len(children)
    depth = np.full(N, -1, dtype=np.int32)

    q = deque()
    for r in roots:
        depth[r] = 0
        q.append(r)

    while q:
        u = q.popleft()
        for v in children[u]:
            depth[v] = depth[u] + 1
            q.append(v)

    bad = np.where(depth < 0)[0]
    if bad.size > 0:
        depth[bad] = 0

    return depth


def euler_tour_times(children, roots):
    """
    Compute entry/exit times (tin/tout) for each node.
    Unreachable nodes (e.g., appended k:UNK) get singleton intervals.
    """
    N = len(children)
    tin = np.full(N, -1, dtype=np.int32)
    tout = np.full(N, -1, dtype=np.int32)
    t = 0

    def dfs(u):
        nonlocal t
        tin[u] = t
        t += 1
        for v in children[u]:
            dfs(v)
        tout[u] = t
        t += 1

    for r in roots:
        if tin[r] == -1:
            dfs(r)

    bad = np.where(tin < 0)[0]
    for u in bad:
        tin[u] = t
        t += 1
        tout[u] = t
        t += 1

    return tin, tout



In [5]:

# --------------------------
# Paths (NEW dataset)
# --------------------------
DATASET_DIR_GENUS = Path(
    "/home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training"
    "/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_full_top999"
)

VOCAB_PATH  = DATASET_DIR_GENUS / "taxonomy_vocab.json"
NESTED_PATH = DATASET_DIR_GENUS / "taxonomy_nested.json"

assert VOCAB_PATH.exists(), f"Missing: {VOCAB_PATH}"
assert NESTED_PATH.exists(), f"Missing: {NESTED_PATH}"

TREE_DIR = DATASET_DIR_GENUS / "tree_artifacts"
TREE_DIR.mkdir(parents=True, exist_ok=True)

print("DATASET_DIR_GENUS =", DATASET_DIR_GENUS)
print("TREE_DIR          =", TREE_DIR)

# --------------------------
# Load vocab + nested tree
# --------------------------
names = json.load(open(VOCAB_PATH, "r"))
name2idx = {nm: i for i, nm in enumerate(names)}
N = len(names)

taxonomy_nested = json.load(open(NESTED_PATH, "r"))

print("N taxonomy nodes =", N)
print("Top-level clades:", list(taxonomy_nested.keys())[:10])


# ============================================================
# 1) Build parent pointers and children adjacency from nested dict
# ============================================================



parent, children = build_parent_children_from_nested(taxonomy_nested, name2idx)
roots = [i for i in np.where(parent == -1)[0].tolist() if names[i] in taxonomy_nested]

print("Number of roots (top-level clades) =", len(roots))
print("First 10 roots:", [names[i] for i in roots[:10]])


# ============================================================
# 2) Compute depth (optional but convenient for debugging)
# ============================================================



depth = compute_depth(children, roots)
print("Depth min/max:", int(depth.min()), int(depth.max()))


# ============================================================
# 3) Euler tour times + dense descendant-closure matrix
# ============================================================


tin, tout = euler_tour_times(children, roots)

def build_descendant_matrix_dense(tin, tout, dtype=np.uint8):
    """
    Dense descendant-closure matrix:
      M[i, j] = 1 iff i is ancestor of j (including i==j)
    """
    N = len(tin)
    M = np.zeros((N, N), dtype=dtype)
    for i in tqdm(range(N), desc="Building descendant matrix (dense)"):
        M[i, :] = ((tin[i] <= tin) & (tout <= tout[i])).astype(dtype)
    return M

M = build_descendant_matrix_dense(tin, tout, dtype=np.uint8)

print("Descendant matrix shape:", M.shape, "dtype:", M.dtype)
print("Diagonal sum (should be N):", int(np.trace(M)))
print("Nonzero entries:", int(M.sum()))


# ============================================================
# 4) Save base tree artifacts (GENUS dataset)
# ============================================================

np.save(TREE_DIR / "parent.npy", parent)
np.save(TREE_DIR / "depth.npy", depth)
np.save(TREE_DIR / "tin.npy", tin)
np.save(TREE_DIR / "tout.npy", tout)

desc_path = TREE_DIR / "descendant_matrix.npy"
np.save(desc_path, M)
print("Saved:", desc_path)

readme_path = TREE_DIR / "README_descendants.md"
with open(readme_path, "w") as f:
    f.write(
        "# Descendant matrix (ancestor/descendant closure)\n\n"
        "Files in this folder are derived from taxonomy_nested.json and taxonomy_vocab.json.\n\n"
        "## descendant_matrix.npy\n"
        "Let `names = taxonomy_vocab.json` (length N).\n"
        "The matrix `M` has shape [N, N] and is defined as:\n"
        "`M[i, j] = 1` iff node `names[j]` is equal to or a descendant of node `names[i]`.\n\n"
        "This matches the old ETE3 implementation, but uses an Euler tour (tin/tout) for speed.\n"
    )
print("Saved:", readme_path)


# ============================================================
# 5) UNK-extend vocab + descendant matrix + rank_idx (GENUS dataset)
#     (matches your existing logic)
# ============================================================

BASE_VOCAB_PATH = DATASET_DIR_GENUS / "taxonomy_vocab.json"
BASE_M_PATH     = TREE_DIR / "descendant_matrix.npy"

NEW_VOCAB_PATH  = TREE_DIR / "taxonomy_vocab_with_unk.json"
NEW_M_PATH      = TREE_DIR / "descendant_matrix_with_unk.npy"
RANK_IDX_PATH   = TREE_DIR / "rank_idx.npy"

with open(BASE_VOCAB_PATH, "r") as f:
    vocab_old = json.load(f)

M_old = np.load(BASE_M_PATH)
T_old = len(vocab_old)
assert M_old.shape == (T_old, T_old), "Mismatch between vocab and descendant matrix"
print(f"Loaded base taxonomy: T_old={T_old}")

RANK_CHAR_TO_IDX = {"k":0, "p":1, "c":2, "o":3, "f":4, "g":5, "s":6}

rank_idx_old = np.empty(T_old, dtype=np.int64)
for i, name in enumerate(vocab_old):
    c = name[0].lower()
    if c not in RANK_CHAR_TO_IDX:
        raise ValueError(f"Cannot infer rank from token: {name}")
    rank_idx_old[i] = RANK_CHAR_TO_IDX[c]

desired_unk = [f"{r}:UNK" for r in ["k","p","c","o","f","g","s"]]
have = set(vocab_old)

unk_tokens_to_add = [tok for tok in desired_unk if tok not in have]
vocab_new = vocab_old + unk_tokens_to_add
T_new = len(vocab_new)

with open(NEW_VOCAB_PATH, "w") as f:
    json.dump(vocab_new, f, indent=2)

print(f"Extended vocab saved: T_new={T_new} (added {len(unk_tokens_to_add)} UNKs)")
print("UNKs added:", unk_tokens_to_add)

rank_idx_new = np.empty(T_new, dtype=np.int64)
rank_idx_new[:T_old] = rank_idx_old
for j, tok in enumerate(unk_tokens_to_add, start=T_old):
    rank_idx_new[j] = RANK_CHAR_TO_IDX[tok[0].lower()]

M_new = np.zeros((T_new, T_new), dtype=M_old.dtype)
M_new[:T_old, :T_old] = M_old

unk_id_by_rank = {}
for tok in desired_unk:
    idx = vocab_new.index(tok)
    unk_id_by_rank[tok[0].lower()] = idx

# Link UNK_r (r>=1) as child of ALL base nodes at rank r-1
for r_char, r in [("p",1), ("c",2), ("o",3), ("f",4), ("g",5), ("s",6)]:
    unk_id = unk_id_by_rank[r_char]
    parent_rank = r - 1

    parents = np.where(rank_idx_old == parent_rank)[0]

    # exclude k:UNK from being a parent of p:UNK (if present in base)
    if parent_rank == 0 and "k:UNK" in vocab_old:
        kunk_id_base = vocab_old.index("k:UNK")
        parents = parents[parents != kunk_id_base]

    if parents.size == 0:
        print(f"[WARN] No parents found at rank {parent_rank} for {r_char}:UNK")
        continue

    M_new[parents, unk_id] = 1

# Chain UNKs: k:UNK → p:UNK → ... → s:UNK
chain = ["k","p","c","o","f","g","s"]
for a, b in zip(chain[:-1], chain[1:]):
    M_new[unk_id_by_rank[a], unk_id_by_rank[b]] = 1

np.fill_diagonal(M_new, 1)

np.save(NEW_M_PATH, M_new)
np.save(RANK_IDX_PATH, rank_idx_new)

print("Saved UNK-extended hierarchy artifacts:")
print(" -", NEW_VOCAB_PATH)
print(" -", NEW_M_PATH)
print(" -", RANK_IDX_PATH)


DATASET_DIR_GENUS = /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_full_top999
TREE_DIR          = /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_full_top999/tree_artifacts
N taxonomy nodes = 6115
Top-level clades: ['k:Bacteria', 'k:Archaea']
Number of roots (top-level clades) = 2
First 10 roots: ['k:Archaea', 'k:Bacteria']
Depth min/max: 0 6


Building descendant matrix (dense): 100%|██████████| 6115/6115 [00:00<00:00, 141249.19it/s]

Descendant matrix shape: (6115, 6115) dtype: uint8
Diagonal sum (should be N): 6115
Nonzero entries: 36501
Saved: /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_full_top999/tree_artifacts/descendant_matrix.npy
Saved: /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_full_top999/tree_artifacts/README_descendants.md
Loaded base taxonomy: T_old=6115
Extended vocab saved: T_new=6121 (added 6 UNKs)
UNKs added: ['p:UNK', 'c:UNK', 'o:UNK', 'f:UNK', 'g:UNK', 's:UNK']
Saved UNK-extended hierarchy artifacts:
 - /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_full_top999/tree_artifacts/taxonomy_vocab_with_unk.json
 - /home/hernan_melmoth/Documents/phd_work/Microbeatlas_preprocess_training/level_97/silva-138.2/incomplete_genus_silva_sintax/dataset_ful